### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by SimplyCorey** [andrew-mestas/swalExtend#13]
Thanks for the package.   Is there anyway you can put it on npm so i can pull it down through my dependency manager?

Thanks!

**Comment by LuisDiazUgena** [comment]
This will be a really nice idea.

**Comment by andrew-mestas** [comment]
That's a good idea I'll see if I can add that in a future version.

Also apologies for such a long time to respond I went traveling and started a new job in January. It's been very busy since then and I haven't had the time to check my personal projects.
