### ISSUE TITLE
How to Apply swalExtend?

### ISSUE THREAD

**Issue by MightyFlea2017** [andrew-mestas/swalExtend#2]
Could you help define a little more how to apply the code? Not quite sure where/how to use it. Right now I call on the JS for swal and then call on it to open the alert. This code works fine:

```
<script src="/SweetAlerts/sweetalert.min.js"></script>
<link rel="stylesheet" type="text/css" href="/SweetAlerts/sweetalert.css">
```

And in my javascript function:

`swal({   title: "Warnings",   text: "Please confirm the following items are correct before submitting:\n\n" + sWarnings,   type: "info",   showCancelButton: true,   confirmButtonColor: "#DD6B55",   confirmButtonText: "Save and Submit",   closeOnCancel: true, closeOnConfirm: false }, function(){ SaveInfo(1) });`

How do I replace this with three buttons using swalExtend (Save Progress / Save and Submit / Cancel), but still maintain the same title and text as my original swal?

**Comment by alwinkpc** [comment]
Hi. Let me help you with this as I was having the same question and by looking at the code I was able to understand it. You need to create a simple swal dialog (no buttons) and then call `swalExtend()` class as this appends the buttons. You need to handle function events and close

    swal({
        title: "Warnings",
        text: "Please confirm the following items are correct before submitting:\n\n" + sWarnings,
        type: "info"
    );

    swalExtend({
        hasCancelButton: true,
        buttonNum: 2,
        buttonNames: ["one", "two"],
        // className: ["redButton", "blueButton"],
        clickFunctionList: [
            function() {
                console.debug('ONE BUTTON');
            }, 
            function() {
                console.debug('TWO BUTTON');
            }
        ]
    });

**Comment by andrew-mestas** [comment]
This is now updated please refer to README for current implementation.
