### ISSUE TITLE
With the extra buttons, how can I close the dialog?

### ISSUE THREAD

**Issue by flyrev** [andrew-mestas/swalExtend#3]
When pressing "maybe delete" here https://codepen.io/andrew-mestas/pen/BWNXRN the dialog is not closed.

What do I need to add for it to close it?

**Comment by andrew-mestas** [comment]
It looks like initially the event listeners are not being set for the extra buttons after a user closes the modal the second time it is open the buttons work correctly. I'm looking into this issue.

update: going to push a change that should take care of this scenario. It's a little hacky, but it should unblock you in the mean time.

**Comment by andrew-mestas** [comment]
Addressed in latest commit 4c97432d706a982f7485458cbb82d945c47ffd32
