### ISSUE TITLE
the added buttons still execute the code in the original

### ISSUE THREAD

**Issue by zoinkydoink** [andrew-mestas/swalExtend#4]
i also had to specifiy hasCallback because otherwise I was getting an error as per your code (not even sure why this check is here)

`  if (params.hasCallback === undefined) {
        swal("swalExtend", "hasCallback property is not defined.", "error");
        return;
    }`

but here is the code i am having issued with, clicking "yes deleted it" (original button) only logs "ORIGINAL BUTTON" to console but both of the other buttons added by your extension causes "ORIGINAL BUTTON" and "ONE BUTTON" or "TWO BUTTON" to fire.

3 buttons should each have either own executions and not add execution of others, tested in Edge and ltest chrome.

    var swalFunction = function () {
    swal({
        title: "Are you sure?",
        text: "You will not be able to recover this imaginary file!",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes, delete it!",
        closeOnConfirm: true
    },
        function () {
            console.debug('ORIGINAL BUTTON');
        });
    };

    function confirmEventDelete(id, type, typeID, isRepeated, parentUniqueID) {
    if (isRepeated == "True") {
        swalExtend({
            swalFunction: swalFunction,
            hasCancelButton: true,
            buttonNum: 2,
            hasCallback:false,
            buttonNames: ["maybe delete", "probably/partially delete"],
            clickFunctionList: [
                function () {
                    console.debug('ONE BUTTON');
                },
                function () {
                    console.debug('TWO BUTTON');
                }
            ]
        });

      } else {

        confirmMessage("Are you sure you want to delete the event!", id, deleteEvent, type, typeID);
      }
    }

**Comment by andrew-mestas** [comment]
I looked into this, the method which creates the click listeners from sweet alert changed from when this was originally created. I have modified swalExtend to account for this in the latest commit.
