### ISSUE TITLE
Error: hasCallback property is not defined.

### ISSUE THREAD

**Issue by LamaBimal** [andrew-mestas/swalExtend#5]
While implementing, the swalExtend it throws the following error:
hasCallback property is not defined. How could i resolve it.

Implementation is something like this:-
  var alertfunction = function(){
                swal({
                        title: "Open New Cluster",
                        text: "Would you like to resume the jobs with new Cluster?",
                        type: "info",
                        showCancelButton: true,
                        allowEscapeKey:false,
                        allowOutsideClick:false,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Yes",
                        cancelButtonText: "No"

                    },
                    function(isConfirm){
                        json['startNewCluster']= isConfirm;
                        if(!isConfirm)
                        {
                            json['clusterId']=clusterId;
                        }
                        colorTrace(json,"blue");
                    
                    });
            }
            swalExtend({
                swalFunction:alertfunction,
                hasCancelButton:true,
                buttonNum:2,
                buttonNames:["One","two"],
                clickFunctionLists:[
                    function(){
                        colorTrace("One","Red");
                    },function(){
                        colorTrace("two","green");
                    }
                ]
            })

**Comment by andrew-mestas** [comment]
Short version: 
I would try adding hasCallback: true to your swalExtend object.

Longer explanation: 
This is a key value pair that you need to define in the swal extend object, the idea is if the main sweet alert declaration has a callback you could choose to change it with swal extend I'm debating on removing this. Sorry for the late response I've been in the hospital just got back a few days ago.

**Comment by Lwbcr7** [comment]
Hi Andrew, i got the same problem and i added 'hasCallback: true' to the swalExtend object as you said, but i still not work and another error comes out:
swalExtend.js:44 Uncaught TypeError: Cannot read property 'cloneNode' of undefined at swalExtend (swalExtend.js:44).

**Comment by andrew-mestas** [comment]
This option has been removed until a future time. 04fcde87913829482824039f747d8e2c0eb62405

@Lwbcr7 Can you send an example of your swalExtend code? [CodePen](https://codepen.io/andrew-mestas/pen/Kqqjzo?editors=0110)
