### ISSUE TITLE
Humble recommendation to accommodate bootstrap or other css class stylings

### ISSUE THREAD

**Issue by JTCE** [andrew-mestas/swalExtend#6]
A humble suggestion as I do not have time for PR's right now.

Replace line 1 with line 2 to allow for custom classes. I'm using bootstrap-sweetalert and it was appending all the classes, ie: btn-danger btn-success, when all I wanted was to set a new class btn-success.

1. `div.className = cl + " divbutton " + add + " swalExtendButton";`
2. `div.className = params.classNames[i] == undefined ? cl + " divbutton " + add + " swalExtendButton" : "confirm " + add + " divbutton swalExtendButton";`

**Comment by andrew-mestas** [comment]
Done and thank you for the feedback.
b0c72fc

**Comment by JTCE** [comment]
Closing as it was added to swalExtend.js. 
Thank you Andrew!
